Add example of deploying a smart contract via a proposal
DA0-DA0/docs pull request #5
Opened 2021-12-20 05:59 UTC by ezekiiel

2021-12-20 23:41 UTC, elsehow requested changes
Fantastic PR, and what a compelling usecase. 

I've left a few specific comments in the notes. More generally, I'd say this doc is trying to achieve a few different DAOs.

1.  Launch a DAO with a DAO (cool)!
2. Launch a smart contract with a DAO.
3. Critique & improve upon ENS.

1 and 2 are substantively the same. In fact, a cool way to frame this would be, "DAOs can launch smart contracts. In fact, since a DAO is itself a smart contract, DAOS can launch DAOs!" You can draw on the ENS critique to motivate and make concrete why we might want to do this, but I'd keep it more parenthetical and explanatory than central to the doc.

Please let me know if you have any questions about any of my comments. This is a fantastic contribution. I look forward to merging it.

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +DAO-DAO. By the end of this example you'll have deployed a new DAO via
For consistency: "DAO DAO" not "DA0-DA0"

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +DAO-DAO. By the end of this example you'll have deployed a new DAO via
Consitency: "DAO DAO" not "DA0-DA0"

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +The Ethereum Name Service is currently controlled by a four of seven
This comes a bit out of nowhere. Can we start by, in the intro, framing this around the Ethereum name service?

Alternatively (and my personal preference), can we state in the intro that we'll "create a DAO via a DAO proposal," then move this Ethereum name system stuff into a tip?

```
:::tip
Why start a DAO with a DAO proposal? [generic explanation of why this might be desireable]. [mention specific case of ENS, perhaps linking to a blog post of some sort outside the docs for more information]
:::
```

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +Smart contracts are typically structured such that their owner (the
Good thing for the potential tip above.

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +For at the time of writing the DAO-DAO smart contract is deployed with
Do you mean, "At the time of writing?"

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +In order to deploy the contract DAO-DAO expects a more general
More general than what? I think you probably mean "DAO DAO expects a `WasmMsg`, which can encapsulates all the ways one might interact with a smart contract on Juno."

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +your DAO in the "Info" tab on your DAO's homepage.
Can we link to something that describes what admin means in the context of this contract?

2021-12-20 23:41 UTC, elsehow commented on docs/examples/contract-deployment.md
> +		  ...TODO
I think the `TODO` is a bit confusing. I'd expect to see:

```json
{
  "wasm": {
    "instantiate": {
      "admin": "juno147huky2j39qccdw4a0j68y8xrpg7wwqfvkm29qfmsecn5nu6rl8qsle7gk",
      "code_id": 280,
      "label": "baby dao",
      "msg": {} // TODO - We'll create this message below.
    }
  }
}
```

2021-12-29 00:47 UTC, ezekiiel commented
@elsehow gave it another pass. Thanks for the great feedback! Let me know if you have more thoughts :)

2021-12-29 03:00 UTC, JakeHartnell approved these changes
Looking forward to what @elsehow says, but this is an AMAZING thing to document.

2021-12-29 15:58 UTC, elsehow approved these changes

2021-12-29 15:59 UTC, elsehow commented
LGTM! Amazing contribution @ezekiiel. Thank you!

2021-12-29 15:59 UTC, merged